
package JFrams;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class ManageBooks extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    public ManageBooks() {
        initComponents();
        
        getBooksData();  
    }
    public boolean setValues(){
        boolean is_add = false;
        String book_id = bookidTF.getText();
        String book_name = booknameTF.getText();
        String book_author = bookauthorTF.getText();
        String book_quantity = bookquantityTF.getText();
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pstm = con.prepareStatement("insert into book (id,name,author,quantity) values (?,?,?,?)");
            pstm.setString(1, book_id);
            pstm.setString(2, book_name);
            pstm.setString(3, book_author);
            pstm.setString(4, book_quantity);   
            int row_count = pstm.executeUpdate();
            
           if(row_count>0){
                is_add = true;
           } 
           else{
                is_add = false;               
           }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return is_add;
    }
    public void getBooksData(){
        DefaultTableModel model;
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pstm = con.prepareStatement("select * from book");
            ResultSet rs = pstm.executeQuery();
            
            while(rs.next()){
                String book_id = rs.getString(1);
                String book_name = rs.getString(2);
                String book_author = rs.getString(3);
                String book_quantity = rs.getString(4);
                
                Object obj[] = {book_id,book_name,book_author,book_quantity};
                model = (DefaultTableModel)table3.getModel();
                model.addRow(obj);

            }
        }
        catch(Exception e){
            e.printStackTrace();
        }

        
    }
    public void clearTable(){
        
        DefaultTableModel model = (DefaultTableModel)table3.getModel();
        model.setRowCount(0);
    }
    
    public boolean updateValues(){
        boolean is_update = false;
        String book_id = bookidTF.getText();
        String book_name = booknameTF.getText();
        String book_author = bookauthorTF.getText();
        String book_quantity = bookquantityTF.getText();    
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pstm = con.prepareStatement("update book set name = ?, author = ?, quantity = ?where id = ?");
            pstm.setString(1, book_name);
            pstm.setString(2, book_author);
            pstm.setString(4, book_id);
            pstm.setString(3, book_quantity);
            
            int row_count = pstm.executeUpdate();
            
            if(row_count > 0){
                is_update = true;
            }
            else{
                is_update = false;
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return is_update;
    }
    
    public boolean deleteValues(){
        boolean is_delete = false;
        String book_id = bookidTF.getText();
        String book_name = booknameTF.getText();
        String book_author = bookauthorTF.getText();
        String book_quantity = bookquantityTF.getText();  
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pstm = con.prepareStatement("delete from book where id = ?");
            pstm.setString(1, book_id);
            int row_count = pstm.executeUpdate();
            
            if(row_count > 0){
                is_delete = true;
            }
            else{
                is_delete = false;
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return is_delete;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bookidTF = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bookauthorTF = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bookquantityTF = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle4 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle5 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle6 = new necesario.RSMaterialButtonCircle();
        booknameTF = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table3 = new rojeru_san.complementos.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 4, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        jLabel7.setBackground(new java.awt.Color(204, 255, 0));
        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 70, 60));

        jLabel11.setBackground(java.awt.Color.gray);
        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Book Id :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel8.setBackground(java.awt.Color.gray);
        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 50, 60));

        jLabel13.setBackground(java.awt.Color.gray);
        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Book Name :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel12.setBackground(java.awt.Color.gray);
        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 50, 60));

        bookidTF.setBackground(new java.awt.Color(0, 102, 102));
        bookidTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bookidTF.setForeground(new java.awt.Color(204, 255, 204));
        bookidTF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        bookidTF.setPhColor(new java.awt.Color(255, 255, 255));
        bookidTF.setPlaceholder("Enter Book Id ...");
        bookidTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidTFActionPerformed(evt);
            }
        });
        jPanel1.add(bookidTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 250, -1));

        jLabel15.setBackground(java.awt.Color.gray);
        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Author Name :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel14.setBackground(java.awt.Color.gray);
        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 50, 60));

        bookauthorTF.setBackground(new java.awt.Color(0, 102, 102));
        bookauthorTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bookauthorTF.setForeground(new java.awt.Color(204, 255, 204));
        bookauthorTF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        bookauthorTF.setPhColor(new java.awt.Color(255, 255, 255));
        bookauthorTF.setPlaceholder("Enter Author Name ...");
        bookauthorTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookauthorTFFocusLost(evt);
            }
        });
        bookauthorTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookauthorTFActionPerformed(evt);
            }
        });
        jPanel1.add(bookauthorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 260, -1));

        jLabel16.setBackground(java.awt.Color.gray);
        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 50, 60));

        jLabel17.setBackground(java.awt.Color.gray);
        jLabel17.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Quantity :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        bookquantityTF.setBackground(new java.awt.Color(0, 102, 102));
        bookquantityTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bookquantityTF.setForeground(new java.awt.Color(204, 255, 204));
        bookquantityTF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        bookquantityTF.setPhColor(new java.awt.Color(255, 255, 255));
        bookquantityTF.setPlaceholder("Enter Quantity ...");
        bookquantityTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookquantityTFFocusLost(evt);
            }
        });
        bookquantityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookquantityTFActionPerformed(evt);
            }
        });
        jPanel1.add(bookquantityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 260, -1));

        rSMaterialButtonCircle4.setBackground(new java.awt.Color(255, 204, 204));
        rSMaterialButtonCircle4.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle4.setText("DELETE");
        rSMaterialButtonCircle4.setFont(new java.awt.Font("Century Schoolbook", 1, 17)); // NOI18N
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 120, 60));

        rSMaterialButtonCircle5.setBackground(new java.awt.Color(255, 204, 204));
        rSMaterialButtonCircle5.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle5.setText("ADD");
        rSMaterialButtonCircle5.setFont(new java.awt.Font("Century Schoolbook", 1, 17)); // NOI18N
        rSMaterialButtonCircle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 120, 60));

        rSMaterialButtonCircle6.setBackground(new java.awt.Color(255, 204, 204));
        rSMaterialButtonCircle6.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle6.setText("UPDATE");
        rSMaterialButtonCircle6.setFont(new java.awt.Font("Century Schoolbook", 1, 17)); // NOI18N
        rSMaterialButtonCircle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 120, 60));

        booknameTF.setBackground(new java.awt.Color(0, 102, 102));
        booknameTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        booknameTF.setForeground(new java.awt.Color(204, 255, 204));
        booknameTF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        booknameTF.setPhColor(new java.awt.Color(255, 255, 255));
        booknameTF.setPlaceholder("Enter Book Name ...");
        booknameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknameTFActionPerformed(evt);
            }
        });
        jPanel1.add(booknameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 720));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(204, 255, 0));
        jLabel9.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 70, 60));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Author", "Quantity"
            }
        ));
        table3.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        table3.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        table3.setColorSelBackgound(new java.awt.Color(255, 204, 51));
        table3.setColorSelForeground(new java.awt.Color(0, 0, 0));
        table3.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        table3.setFuenteFilas(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        table3.setFuenteFilasSelect(new java.awt.Font("Tempus Sans ITC", 1, 19)); // NOI18N
        table3.setFuenteHead(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        table3.setMaximumSize(new java.awt.Dimension(700, 60));
        table3.setRowHeight(35);
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table3);
        if (table3.getColumnModel().getColumnCount() > 0) {
            table3.getColumnModel().getColumn(0).setMinWidth(60);
            table3.getColumnModel().getColumn(1).setMinWidth(400);
            table3.getColumnModel().getColumn(1).setMaxWidth(60);
            table3.getColumnModel().getColumn(2).setMinWidth(220);
            table3.getColumnModel().getColumn(3).setMinWidth(80);
            table3.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 780, 450));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel2.setText("Manage Books");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 360, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 910, 720));

        setSize(new java.awt.Dimension(1355, 722));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void bookidTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookidTFActionPerformed

    private void bookauthorTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookauthorTFFocusLost
        //   if(checkDuplicateValues() == true){
            //     JOptionPane.showMessageDialog(this,"This Email is Already Exist ...");
            //}
    }//GEN-LAST:event_bookauthorTFFocusLost

    private void bookauthorTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookauthorTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookauthorTFActionPerformed

    private void bookquantityTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookquantityTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bookquantityTFFocusLost

    private void bookquantityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookquantityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookquantityTFActionPerformed

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        if(deleteValues() == true){
            JOptionPane.showMessageDialog(this, "Book deleted Successfully");
            clearTable();
            getBooksData();
        }
        else{
            JOptionPane.showMessageDialog(this, "Book did not delete Successfully");            
        }       
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void rSMaterialButtonCircle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle5ActionPerformed
        if(setValues() == true){
            JOptionPane.showMessageDialog(this, "Book Added Successfully");
            clearTable();
            getBooksData();
        }
        else{
            JOptionPane.showMessageDialog(this, "Book did not Add Successfully");            
        }
    }//GEN-LAST:event_rSMaterialButtonCircle5ActionPerformed

    private void rSMaterialButtonCircle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle6ActionPerformed
        if(updateValues() == true){
            JOptionPane.showMessageDialog(this, "The data updated successfully");
            clearTable();
            getBooksData();            
        }
        else{
            JOptionPane.showMessageDialog(this, "data is not updated successfully");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle6ActionPerformed

    private void booknameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booknameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booknameTFActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        int row_num = table3.getSelectedRow();
        TableModel model = table3.getModel();
        bookidTF.setText(model.getValueAt(row_num, 0).toString());
        booknameTF.setText(model.getValueAt(row_num, 1).toString());        
        bookauthorTF.setText(model.getValueAt(row_num, 2).toString());
        bookquantityTF.setText(model.getValueAt(row_num, 3).toString());        
    }//GEN-LAST:event_table3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField bookauthorTF;
    private app.bolivia.swing.JCTextField bookidTF;
    private app.bolivia.swing.JCTextField booknameTF;
    private app.bolivia.swing.JCTextField bookquantityTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle5;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle6;
    private rojeru_san.complementos.RSTableMetro table3;
    // End of variables declaration//GEN-END:variables
}
