
package JFrams;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class ManageStudents extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    public ManageStudents() {
        initComponents();
        
        getStudentData();  
    }
    public boolean setValues(){
        boolean is_add = false;
        String student_id = studentidTF.getText();
        String student_name = studentnameTF.getText();
        String student_contact = studentcontactTF.getText();
        String student_address = studentaddressTF.getText();
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pstm = con.prepareStatement("insert into student (id,name,contact,address) values (?,?,?,?)");
            pstm.setString(1, student_id);
            pstm.setString(2, student_name);
            pstm.setString(3, student_contact);
            pstm.setString(4, student_address);   
            int row_count = pstm.executeUpdate();
            
           if(row_count>0){
                is_add = true;
           } 
           else{
                is_add = false;               
           }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return is_add;
    }
    public void getStudentData(){
        DefaultTableModel model;
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pstm = con.prepareStatement("select * from student");
            ResultSet rs = pstm.executeQuery();
            
            while(rs.next()){
                String student_id = rs.getString(1);
                String student_name = rs.getString(2);
                String student_contact = rs.getString(3);
                String student_address = rs.getString(4);
                
                Object obj[] = {student_id,student_name,student_contact,student_address};
                model = (DefaultTableModel)table4.getModel();
                model.addRow(obj);

            }
        }
        catch(Exception e){
            e.printStackTrace();
        }

        
    }
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel)table4.getModel();
        model.setRowCount(0);
    }
    
    public boolean updateValues(){
        boolean is_update = false;
        String student_id = studentidTF.getText();
        String student_name = studentnameTF.getText();
        String student_contact = studentcontactTF.getText();
        String student_address = studentaddressTF.getText();    
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pstm = con.prepareStatement("update student set name = ?, contact = ?, address = ? where id = ?");
            pstm.setString(4, student_id);
            pstm.setString(1, student_name);
            pstm.setString(2, student_contact);
            pstm.setString(3, student_address);
            
            int row_count = pstm.executeUpdate();
            
            if(row_count > 0){
                is_update = true;
            }
            else{
                is_update = false;
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return is_update;
    }
    
    public boolean deleteValues(){
        boolean is_delete = false;
        String student_id = studentidTF.getText();
        String student_name = studentnameTF.getText();
        String student_contact = studentcontactTF.getText();
        String student_address = studentaddressTF.getText();  
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pstm = con.prepareStatement("delete from student where id = ?");
            pstm.setString(1, student_id);
            int row_count = pstm.executeUpdate();
            
            if(row_count > 0){
                is_delete = true;
            }
            else{
                is_delete = false;
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return is_delete;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        studentidTF = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        studentcontactTF = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        studentaddressTF = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle9 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle7 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle8 = new necesario.RSMaterialButtonCircle();
        studentnameTF = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table4 = new rojeru_san.complementos.RSTableMetro();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 4, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        jLabel7.setBackground(new java.awt.Color(204, 255, 0));
        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 70, 60));

        jLabel11.setBackground(java.awt.Color.gray);
        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Student Id :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel8.setBackground(java.awt.Color.gray);
        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 50, 60));

        jLabel13.setBackground(java.awt.Color.gray);
        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Student Name :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel12.setBackground(java.awt.Color.gray);
        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 50, 60));

        studentidTF.setBackground(new java.awt.Color(0, 102, 102));
        studentidTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        studentidTF.setForeground(new java.awt.Color(204, 255, 204));
        studentidTF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        studentidTF.setPhColor(new java.awt.Color(255, 255, 255));
        studentidTF.setPlaceholder("Enter Student Id ...");
        studentidTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidTFActionPerformed(evt);
            }
        });
        jPanel1.add(studentidTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 250, -1));

        jLabel15.setBackground(java.awt.Color.gray);
        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student Contact :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel14.setBackground(java.awt.Color.gray);
        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 50, 60));

        studentcontactTF.setBackground(new java.awt.Color(0, 102, 102));
        studentcontactTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        studentcontactTF.setForeground(new java.awt.Color(204, 255, 204));
        studentcontactTF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        studentcontactTF.setPhColor(new java.awt.Color(255, 255, 255));
        studentcontactTF.setPlaceholder("Enter Student Contact ...");
        studentcontactTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentcontactTFFocusLost(evt);
            }
        });
        studentcontactTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentcontactTFActionPerformed(evt);
            }
        });
        jPanel1.add(studentcontactTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 260, -1));

        jLabel16.setBackground(java.awt.Color.gray);
        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 50, 60));

        jLabel17.setBackground(java.awt.Color.gray);
        jLabel17.setFont(new java.awt.Font("Rockwell", 1, 19)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Student Address :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        studentaddressTF.setBackground(new java.awt.Color(0, 102, 102));
        studentaddressTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        studentaddressTF.setForeground(new java.awt.Color(204, 255, 204));
        studentaddressTF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        studentaddressTF.setPhColor(new java.awt.Color(255, 255, 255));
        studentaddressTF.setPlaceholder("Enter Student Address ...");
        studentaddressTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentaddressTFFocusLost(evt);
            }
        });
        studentaddressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentaddressTFActionPerformed(evt);
            }
        });
        jPanel1.add(studentaddressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 260, -1));

        rSMaterialButtonCircle9.setBackground(new java.awt.Color(255, 204, 204));
        rSMaterialButtonCircle9.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle9.setText("DELETE");
        rSMaterialButtonCircle9.setFont(new java.awt.Font("Century Schoolbook", 1, 17)); // NOI18N
        rSMaterialButtonCircle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle9ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 120, 60));

        rSMaterialButtonCircle7.setBackground(new java.awt.Color(255, 204, 204));
        rSMaterialButtonCircle7.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle7.setText("ADD");
        rSMaterialButtonCircle7.setFont(new java.awt.Font("Century Schoolbook", 1, 17)); // NOI18N
        rSMaterialButtonCircle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 120, 60));

        rSMaterialButtonCircle8.setBackground(new java.awt.Color(255, 204, 204));
        rSMaterialButtonCircle8.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle8.setText("UPDATE");
        rSMaterialButtonCircle8.setFont(new java.awt.Font("Century Schoolbook", 1, 17)); // NOI18N
        rSMaterialButtonCircle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle8ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 120, 60));

        studentnameTF.setBackground(new java.awt.Color(0, 102, 102));
        studentnameTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        studentnameTF.setForeground(new java.awt.Color(204, 255, 204));
        studentnameTF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        studentnameTF.setPhColor(new java.awt.Color(255, 255, 255));
        studentnameTF.setPlaceholder("Enter Student Name ...");
        studentnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnameTFActionPerformed(evt);
            }
        });
        jPanel1.add(studentnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 720));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(204, 255, 0));
        jLabel9.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 70, 60));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel2.setText("Manage Students");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 400, 100));

        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Contact", "Address"
            }
        ));
        table4.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        table4.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        table4.setColorSelBackgound(new java.awt.Color(255, 204, 51));
        table4.setColorSelForeground(new java.awt.Color(0, 0, 0));
        table4.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        table4.setFuenteFilas(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        table4.setFuenteFilasSelect(new java.awt.Font("Tempus Sans ITC", 1, 19)); // NOI18N
        table4.setFuenteHead(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        table4.setMaximumSize(new java.awt.Dimension(700, 60));
        table4.setRowHeight(35);
        table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table4MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table4);
        if (table4.getColumnModel().getColumnCount() > 0) {
            table4.getColumnModel().getColumn(0).setMinWidth(60);
            table4.getColumnModel().getColumn(0).setMaxWidth(60);
            table4.getColumnModel().getColumn(1).setMinWidth(200);
            table4.getColumnModel().getColumn(2).setMinWidth(150);
            table4.getColumnModel().getColumn(2).setMaxWidth(200);
            table4.getColumnModel().getColumn(3).setMinWidth(400);
            table4.getColumnModel().getColumn(3).setMaxWidth(400);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 830, 440));

        jLabel10.setBackground(new java.awt.Color(204, 255, 0));
        jLabel10.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 70, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 910, 720));

        setSize(new java.awt.Dimension(1355, 722));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void studentidTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidTFActionPerformed

    private void studentcontactTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentcontactTFFocusLost
        //   if(checkDuplicateValues() == true){
            //     JOptionPane.showMessageDialog(this,"This Email is Already Exist ...");
            //}
    }//GEN-LAST:event_studentcontactTFFocusLost

    private void studentcontactTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentcontactTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentcontactTFActionPerformed

    private void studentaddressTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentaddressTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_studentaddressTFFocusLost

    private void studentaddressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentaddressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentaddressTFActionPerformed

    private void rSMaterialButtonCircle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle9ActionPerformed
        if(deleteValues() == true){
            JOptionPane.showMessageDialog(this, "Student deleted Successfully");
            clearTable();
           getStudentData();
        }
        else{
            JOptionPane.showMessageDialog(this, "Student did not delete Successfully");            
        }       
    }//GEN-LAST:event_rSMaterialButtonCircle9ActionPerformed

    private void rSMaterialButtonCircle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle7ActionPerformed
        if(setValues() == true){
            JOptionPane.showMessageDialog(this, "Student Added Successfully");
            clearTable();
            getStudentData();
        }
        else{
            JOptionPane.showMessageDialog(this, "Student did not Add Successfully");            
        }
    }//GEN-LAST:event_rSMaterialButtonCircle7ActionPerformed

    private void rSMaterialButtonCircle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle8ActionPerformed
        if(updateValues() == true){
            JOptionPane.showMessageDialog(this, "The data updated successfully");
            clearTable();
            getStudentData();            
        }
        else{
            JOptionPane.showMessageDialog(this, "data is not updated successfully");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle8ActionPerformed

    private void studentnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnameTFActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table4MouseClicked
        int row_num = table4.getSelectedRow();
        TableModel model = table4.getModel();
        studentidTF.setText(model.getValueAt(row_num, 0).toString());
        studentnameTF.setText(model.getValueAt(row_num, 1).toString());        
        studentcontactTF.setText(model.getValueAt(row_num, 2).toString());
        studentaddressTF.setText(model.getValueAt(row_num, 3).toString());           // TODO add your handling code here:
    }//GEN-LAST:event_table4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle7;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle8;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle9;
    private app.bolivia.swing.JCTextField studentaddressTF;
    private app.bolivia.swing.JCTextField studentcontactTF;
    private app.bolivia.swing.JCTextField studentidTF;
    private app.bolivia.swing.JCTextField studentnameTF;
    private rojeru_san.complementos.RSTableMetro table4;
    // End of variables declaration//GEN-END:variables
}
